### PR TITLE
Mac fix

### PR DESCRIPTION
**Pull request by stephenprater**
i made just enough changes to get this to compile and work on my mac.  fixes the issue I opened earlier today.

### CODE REVIEW

**Comment by Asher-** [comment]
Looks like I accidentally pushed a version in the middle of changes. Hadn't realized that had happened - I will look in to it and make sure the main repository reflects appropriate changes. 

Thanks for letting me know!

**Comment by Asher-** [comment]
Apparently I was working on a detached branch and pushed partial changes since I hadn't merged back in to master. Everything should be fixed now, and the gem on RubyGems should also reflect the changes. Additionally, the gem now includes (as it should have previously) the tests, which should verify that the gem is working appropriately. 

Apologies!

-Asher

**Comment by stephenprater** [comment]
still doesn't seem to be working -  this seems to be an issue with the gemspec packaging the ext/ directory, and the gcc flags not being recognized all the time.  doesn't seem to compile on my arch machine either.  (to be fair - i had to remove -gfull flag to get it to compile on arch even with this patch.)

**Comment by Asher-** [comment]
Fixed now - wasn't appearing for me because my default compiler is clang, not gcc.

**Pull request closed without merging**
